services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    depends_on:
      - db
    command: >
      sh -c "sleep 5 && alembic upgrade head && python -m app.main"

  db:
    image: postgres:16
    restart: always
    env_file:
      - app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

volumes:
  postgres_data:
