"""add ondelete CASCADE

Revision ID: 162dc256b62d
Revises: ba48ec03faee
Create Date: 2025-07-23 18:22:08.022898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162dc256b62d'
down_revision: Union[str, Sequence[str], None] = 'ba48ec03faee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('BannedUsers_user_id_fkey'), 'BannedUsers', type_='foreignkey')
    op.create_foreign_key(None, 'BannedUsers', 'Users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ChatMembers_chat_id_fkey'), 'ChatMembers', type_='foreignkey')
    op.create_foreign_key(None, 'ChatMembers', 'Chats', ['chat_id'], ['chat_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('UserKeys_user_id_fkey'), 'UserKeys', type_='foreignkey')
    op.create_foreign_key(None, 'UserKeys', 'Users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserKeys', type_='foreignkey')
    op.create_foreign_key(op.f('UserKeys_user_id_fkey'), 'UserKeys', 'Users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'ChatMembers', type_='foreignkey')
    op.create_foreign_key(op.f('ChatMembers_chat_id_fkey'), 'ChatMembers', 'Chats', ['chat_id'], ['chat_id'])
    op.drop_constraint(None, 'BannedUsers', type_='foreignkey')
    op.create_foreign_key(op.f('BannedUsers_user_id_fkey'), 'BannedUsers', 'Users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
