"""add ondelete CASCADE v2

Revision ID: 184ebb624a46
Revises: 162dc256b62d
Create Date: 2025-07-23 18:28:43.578227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184ebb624a46'
down_revision: Union[str, Sequence[str], None] = '162dc256b62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('BlockchainBlocks_creator_user_id_fkey'), 'BlockchainBlocks', type_='foreignkey')
    op.create_foreign_key(None, 'BlockchainBlocks', 'Users', ['creator_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('BlockchainTransactions_receiver_id_fkey'), 'BlockchainTransactions', type_='foreignkey')
    op.drop_constraint(op.f('BlockchainTransactions_chat_id_fkey'), 'BlockchainTransactions', type_='foreignkey')
    op.drop_constraint(op.f('BlockchainTransactions_sender_id_fkey'), 'BlockchainTransactions', type_='foreignkey')
    op.create_foreign_key(None, 'BlockchainTransactions', 'Users', ['sender_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'BlockchainTransactions', 'Users', ['receiver_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'BlockchainTransactions', 'Chats', ['chat_id'], ['chat_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ChatMembers_user_id_fkey'), 'ChatMembers', type_='foreignkey')
    op.create_foreign_key(None, 'ChatMembers', 'Users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Contacts_user_id_fkey'), 'Contacts', type_='foreignkey')
    op.create_foreign_key(None, 'Contacts', 'Users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Notifications_user_id_fkey'), 'Notifications', type_='foreignkey')
    op.create_foreign_key(None, 'Notifications', 'Users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('UserSettings_user_id_fkey'), 'UserSettings', type_='foreignkey')
    op.create_foreign_key(None, 'UserSettings', 'Users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserSettings', type_='foreignkey')
    op.create_foreign_key(op.f('UserSettings_user_id_fkey'), 'UserSettings', 'Users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'Notifications', type_='foreignkey')
    op.create_foreign_key(op.f('Notifications_user_id_fkey'), 'Notifications', 'Users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'Contacts', type_='foreignkey')
    op.create_foreign_key(op.f('Contacts_user_id_fkey'), 'Contacts', 'Users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'ChatMembers', type_='foreignkey')
    op.create_foreign_key(op.f('ChatMembers_user_id_fkey'), 'ChatMembers', 'Users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'BlockchainTransactions', type_='foreignkey')
    op.drop_constraint(None, 'BlockchainTransactions', type_='foreignkey')
    op.drop_constraint(None, 'BlockchainTransactions', type_='foreignkey')
    op.create_foreign_key(op.f('BlockchainTransactions_sender_id_fkey'), 'BlockchainTransactions', 'Users', ['sender_id'], ['user_id'])
    op.create_foreign_key(op.f('BlockchainTransactions_chat_id_fkey'), 'BlockchainTransactions', 'Chats', ['chat_id'], ['chat_id'])
    op.create_foreign_key(op.f('BlockchainTransactions_receiver_id_fkey'), 'BlockchainTransactions', 'Users', ['receiver_id'], ['user_id'])
    op.drop_constraint(None, 'BlockchainBlocks', type_='foreignkey')
    op.create_foreign_key(op.f('BlockchainBlocks_creator_user_id_fkey'), 'BlockchainBlocks', 'Users', ['creator_user_id'], ['user_id'])
    # ### end Alembic commands ###
