"""add device_id to RefreshTokens

Revision ID: 1e96b9c2ced3
Revises: c66dae9a2b37
Create Date: 2025-08-05 23:48:36.719846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e96b9c2ced3'
down_revision: Union[str, Sequence[str], None] = 'c66dae9a2b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RefreshTokens', sa.Column('device_id', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RefreshTokens', 'device_id')
    # ### end Alembic commands ###
