"""Add display_name to chat_members

Revision ID: 5247a574d0dd
Revises: 1e96b9c2ced3
Create Date: 2025-08-07 23:44:19.784529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5247a574d0dd'
down_revision: Union[str, Sequence[str], None] = '1e96b9c2ced3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChatMembers', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ChatMembers', 'display_name')
    # ### end Alembic commands ###
