"""add is_activated_acc to Users

Revision ID: ba48ec03faee
Revises: a5a5487dbef2
Create Date: 2025-07-17 15:53:36.153147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba48ec03faee'
down_revision: Union[str, Sequence[str], None] = 'a5a5487dbef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_activated_acc', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_activated_acc')
    # ### end Alembic commands ###
