"""Change password_hash to String(128)

Revision ID: d1872168c44c
Revises: 472913dc2c3e
Create Date: 2025-06-24 16:24:36.277693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1872168c44c'
down_revision: Union[str, Sequence[str], None] = '472913dc2c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'password_hash',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'password_hash',
               existing_type=sa.String(length=128),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
